export const UPDATE_LIST = 'UPDATE_LIST';

export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';

export const CLEAR_OPTIONS = 'CLEAR_OPTIONS';

export const NEXT_PAGE = 'NEXT_PAGE';

export const RESET_PAGE = 'RESET_PAGE';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_DRAWER_VISIBILITY = 'SET_DRAWER_VISIBILITY';

export const SET_MAP_VISIBILITY = 'SET_MAP_VISIBILITY';

export const SET_MAP_COORDINATES = 'SET_MAP_COORDINATES';
